config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions
  resources :tests, only: [:show, :create]
  resources :responses, only: [:show]
  resources :dashboard, only: [:index, :create]
  resources :users
  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	validates :question, presence: true
	validates :optiona, presence: true
	validates :optionb, presence: true
	validates :optionc, presence: true
	validates :optiond, presence: true
	validates :answer, presence: true
	has_and_belongs_to_many :tests
end

app/models/response.rb
class Response < ApplicationRecord
	
	belongs_to :test
	private
		def compute_score

			
		end
end

app/models/test.rb
class Test < ApplicationRecord
	has_and_belongs_to_many :questions
	belongs_to :user
	has_one :response
	enum status: [:unattempted, :attempted]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_create :default_role
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :tests, -> {where ('status = 1')}
  private
    def default_role
    	self.role ='normal'
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		@test = Test.new
	end

	def create
		@test = Test.new(user_id: current_user.id)
		if @test.save
			@test.questions = Question.order("Random()").limit(5)
			redirect_to test_path(@test)
		end
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :authenticate_user!
	def index
		@questions = Question.all.order(created_at: 'desc')
	end

	def new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params)

		if @question.save
			redirect_to questions_path, notice: 'Question Successfully Added'
			
		else
			redirect_to new_question_path
			flash[:danger] = "Question cannot be saved because:#{@question.errors.full_messages}"
		end
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		if @question.update(question_params)
			redirect_to questions_path, notice: 'Question Successfully Updated'
		else
			redirect_to edit_question_path(@question)
			flash[:danger] = "Question cannot be Updated because:#{@question.errors.full_messages}"
		end
		
	end
	def destroy
		@question = Question.find(params[:id])
		if @question.destroy
			redirect_to questions_path, notice: 'Question Successfully Deleted'
		end
	end

	private
		def question_params
			params.require(:question).permit(:question, :optiona, :optionb, :optionc, :optiond, :answer)
		end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
	before_action :authenticate_user!
	def show
		@test = Test.find(params[:id])
		@response = @test.response
		@questions = @test.questions

	end
	
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
	before_action :authenticate_user!
	def show
		@test = Test.find(params[:id])
		@response = Response.new
	end

	def create
		@response = Response.new(response_params)
		if @response.save
			calculated_score = 0 #initial score = 0
			@response_1 = @response[:response_1]
			@response_2 = @response[:response_2]
			@response_3 = @response[:response_3]
			@response_4 = @response[:response_4]
			@response_5 = @response[:response_5]

			num = 0 #array counter
			answer = Array.new
			@response.test.questions.each do |question|
				answer[num] = question.answer
				num += 1
			end

			if @response_1 == answer[0]
				calculated_score+=10
			end
			if @response_2 == answer[1]
				calculated_score+=10
			end
			if @response_3 == answer[2]
				calculated_score+=10
			end
			if @response_4 == answer[3]
				calculated_score+=10
			end
			if @response_5 == answer[4]
				calculated_score+=10
			end

			@response.score = calculated_score
			@response.save
			@response.test.attempted!
			redirect_to root_path, notice: "Your Test Score is #{calculated_score}"
			
		end
		
	end

	private
		def response_params
			params.require(:response).permit(:response_1, :response_2, :response_3, :response_4, :response_5, :test_id)
			
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
		@users = User.all.where(role: 'normal')
	end
	
	def show
		@tests = User.find(params[:id]).tests.order(created_at: 'desc')

		@max = 0
		@min = 50
		@sum = 0
		@count = 0
		@average = 0
		@tests.each do |test|
			min = 50
			if test.response.score > @max 
				@max = test.response.score
			end
			if test.response.score < @min
				@min = test.response.score
			end
			@sum += test.response.score
			@count += 1
		end
		@sum = @sum.to_f
		@average = @sum/@count
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_form.html.erb
<%= form_for @test, url: {action: "create"} do |f| %>
	<%= f.submit "Start Test", class: 'btn btn-primary' %>
<% end %>

app/views/dashboard/index.html.erb
<div class = "container">
	<% if user_signed_in? %>
		<div class="jumbotron">
		<% if current_user.role == 'admin' %>
			<p>
			<%= link_to "All Questions" , questions_path %>|
			<%= link_to "All Users" , users_path %>|
			</p><hr>
		 
		 <center><h3>Add Questions Here</h3></center>
	  	 <center><p><%= link_to "Add Now" , new_question_path, class: 'btn btn-primary btn-lg' %></p></center>
	  	 <% else %>
	  	 <p><%= link_to "My Profile", user_path(current_user) %> </p>
	  	  <center><h3>Are You Ready to Take the Test?</h3></center>
	  	 <center><p><%= render "form" %></p></center>
	  	 <% end %>

	  	 </div>
	  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizUp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "jquery.rails.js" %>
  </head>

  <body>

  <div class="navbar  navbar-inverse">
    <div class="navbar-class">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><%= link_to "QUIZUP", root_path, class: 'navbar-brand' %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% if user_signed_in? %>
        Signed in as <%= current_user.email %> |
        <%= link_to "Sign out" , destroy_user_session_path, method: 'delete' %>

        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %>
        <% end %>

        <% flash.each do |k,v| %>
        <div class="alert alert-success" role="alert"><center><%= v %></center> </div>
        <% end %>
  </div>


  


    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, html: {class: 'form-horizontal'} do |f| %>
	<div class="form-group">
		<%= f.label :question , class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :question, class: 'form-control', placeholder: 'Enter Question Statement' %>
		</div>
	</div><br>

	<div class="form-group">
		<%= f.label :optiona , class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :optiona, class: 'form-control', placeholder: 'Enter First Option' %>
		</div>
	</div><br>
	<div class="form-group">
		<%= f.label :optionb , class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :optionb, class: 'form-control', placeholder: 'Enter Second Option ' %>
		</div>
	</div><br>
	<div class="form-group">
		<%= f.label :optionc , class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :optionc, class: 'form-control', placeholder: 'Enter Third Option' %>
		</div>
	</div><br>
	<div class="form-group">
		<%= f.label :optiond , class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :optiond, class: 'form-control', placeholder: 'Enter Fourth Option' %>
		</div>
	</div><br>
	<div class="form-group">
		<%= f.label :answer , class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :answer, class: 'form-control', placeholder: "Enter correct option 'a','b','c' or 'd'" %>
		</div>
	</div><br>
	<div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit "Save", class: 'btn btn-primary' %>
		</div>
	</div>

<% end %>

app/views/questions/edit.html.erb
<div class="container">
<div class="jumbotron">
	<%= render 'form' %>
</div>
</div>

app/views/questions/index.html.erb
<center><h5><%= link_to "Add more Questions", new_question_path %></h5></center><hr>
<div class="container">
	<% @question_no = 1 %>
	<% @questions.each do |question| %>
	<h4>
		<b><%= @question_no %>)</b>
		<b><%= question.question %></b>
	</h4>

	a.<%= question.optiona %><br>
	b.<%= question.optionb %><br>
	c.<%= question.optionc %><br>
	d.<%= question.optiond %><br>
	Correct Answer <b>option:<%= question.answer %></b><br>

	<%= link_to "Edit", edit_question_path(question.id) %>|
	<%= link_to "Delete", question, data: {confirm: "Are you sure to delete Question: " + question.question + ""} ,:method => :delete%><hr>
	<% @question_no+= 1 %>
<% end %>
</div>

app/views/questions/new.html.erb
<div class="container">
<div class="jumbotron">
	<%= render 'form' %>
</div>
</div>

app/views/responses/show.html.erb
<div class="container">
	<center>
	<h4>Marks scored on this test: <b><%= @response.score %></b> out of <b>50</b></h4><br>
	</center><hr>
	<b>The submitted answers were:<b/><br>
	<h5>Answer to Question no 1:<b><%= @response.response_1%></b></h5>
	<h5>Answer to Question no 2:<b><%= @response.response_2%></b></h5>
	<h5>Answer to Question no 3:<b><%= @response.response_3%></b></h5>
	<h5>Answer to Question no 4:<b><%= @response.response_4%></b></h5>
	<h5>Answer to Question no 5:<b><%= @response.response_5%></b></h5><hr>

	<% question_no = 1 %>
	<% @questions.each do |question| %>
	<h4>
		<b><%= question_no %>)</b>
		<b><%= question.question %></b>
	</h4>

	<h5>a.<%= question.optiona %></h5>
	<h5>b.<%= question.optionb %></h5>
	<h5>c.<%= question.optionc %></h5>
	<h5>d.<%= question.optiond %></h5>
	Correct Answer <b>option:<%= question.answer %></b><hr>

	
	<% question_no+= 1 %>
<% end %>
</div>

app/views/users/index.html.erb
<center><h3><b>Users List:</h3></b></center><hr>
<div class="container">
	<% @users.each do |user| %>
		<%= link_to user.email, user_path(user) %><hr>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
	<center>
		<h2><b>Profile for <a><%= current_user.email %></a></b></h2>
	</center>
	<table class="table table-hover table-bordered">
		<tr>
			<td><b> Maximum Score is:</b></td>
			<td><b><%= @max %></b></td>
		</tr>
		<tr>
			<td><b> Average Score is:</b></td>
			<% if @average.nan? ==false %>
				<td><b><%= @average %></b></td>
			<% else %>
			<td><b><%= 0 %></td></b>
			<% end %>

		</tr>
		<tr>
			<td><b> Minimum Score is:</b></td>
			<% if @count != 0 %>
				<td><b><%= @min %></b></td>
			<% else %>
			<td><b><%= 0 %></td></b>
			<% end %>
		</tr>
	</table>
	<center>
		<h5><b>List of tests appeared:</b></h5>
		<h6>[Click on the test to view the submitted response]</h6>
	</center>
	<% num = @tests.length %>
	<% @tests.each do |test| %>
		<%= link_to "Test no: #{num}", response_path(test.id) %>
		<% test.id %><hr>
		<% num -= 1 %>
	<% end %>
</div>